// Icon type definitions for external consumption
// This is a self-contained type that doesn't depend on JSON imports
// to ensure it works correctly in consuming projects

export type IconName = 
  | 'add'
  | 'addRing'
  | 'arrowDown'
  | 'arrowLeft'
  | 'arrowRight'
  | 'arrowUp'
  | 'back'
  | 'bell'
  | 'cancel'
  | 'caret'
  | 'caretDown'
  | 'caretUp'
  | 'check'
  | 'checkRing'
  | 'close'
  | 'copy'
  | 'crossCircle'
  | 'directionRight'
  | 'edit'
  | 'export'
  | 'fileDocSearch'
  | 'filter'
  | 'info'
  | 'lamp'
  | 'lineOut'
  | 'link'
  | 'menu'
  | 'message'
  | 'order'
  | 'paper'
  | 'pause'
  | 'play'
  | 'playBack'
  | 'refresh'
  | 'remove'
  | 'search'
  | 'star'
  | 'starFilled'
  | 'table'
  | 'trash'
  | 'userBox'
  | 'view'
  | 'viewHide'

// Also export icons data for runtime use
export { default as iconsData } from '../styles/icons.json'
